name: emconnect
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1


platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: ">=3.1.3 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
 flutter:
    sdk: flutter
 intl: ^0.20.1
 convert: ^3.1.1
 expandable: ^5.0.1
 cupertino_icons: ^1.0.2
 permission_handler: ^12.0.0+1
 device_info_plus: ^11.0.0
 universal_ble: ^0.19.0
 url_launcher: ^6.1.10
 flutter_native_splash: ^2.3.0
 shared_preferences: ^2.1.0
 package_info_plus: ^8.1.2
 provider: ^6.1.2
 file_picker: ^10.1.2
 protobuf: ^4.0.0
 tuple: ^2.0.2
 
 # Use mobile_scanner only for Android, comment for iOS
 mobile_scanner: ^7.0.0

# Use flutter_barcode_scanner only for iOS, comment for Android
#  flutter_barcode_scanner: ^2.0.0
    
  
dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  path_provider: ^2.1.4
  flutter_launcher_icons: ^0.14.3

flutter_native_splash:
  color: "#42a5f5" # Background color
  image: assets/splash.png # Splash image
  android: true # Enable Android support
  ios: true # Enable iOS support
  web: true # Enable web support

flutter_icons:
  android: true
  ios: true
  image_path: "assets/app_icon.png"
  adaptive_icon_background: "#ffffff"
  
flutter:
  uses-material-design: true
  assets:
    - assets/splash.png
    - assets/about_logo.png
    - assets/EMBC22.png
    - assets/EMBP01.png
    - assets/characteristic_uuids.yaml